"""baseline schema

Revision ID: c8364ca2a717
Revises: 
Create Date: 2026-08-25 03:12:42.910608
"""
from alembic import op
import sqlalchemy as sa


revision = 'c8364ca2a717'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('is_side_loading', sa.Boolean(), nullable=False),
    sa.Column('gutter_mm', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insert_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('width_pockets', sa.Integer(), nullable=False),
    sa.Column('height_pockets', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcgplayer_product_id', sa.Integer(), nullable=False),
    sa.Column('sub_type_name', sa.String(length=64), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('direct_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcgplayer_product_id', 'sub_type_name', 'observed_on', 'source', name='uq_price_point')
    )
    with op.batch_alter_table('price_point', schema=None) as batch_op:
        batch_op.create_index('ix_price_observed_on', ['observed_on'], unique=False)

    # current_price: latest observed_on per (tcgplayer_product_id, sub_type_name). Every read
    # path should use this rather than re-deriving the max date -- see docs/02-data-model.md.
    op.execute(
        """
        CREATE VIEW current_price AS
        SELECT p.*
        FROM price_point p
        INNER JOIN (
            SELECT tcgplayer_product_id, sub_type_name, MAX(observed_on) AS max_observed_on
            FROM price_point
            GROUP BY tcgplayer_product_id, sub_type_name
        ) latest
        ON p.tcgplayer_product_id = latest.tcgplayer_product_id
        AND p.sub_type_name = latest.sub_type_name
        AND p.observed_on = latest.max_observed_on
        """
    )

    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptcg_set_id', sa.String(length=32), nullable=False),
    sa.Column('tcgplayer_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.Column('printed_total', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('ptcgo_code', sa.String(length=16), nullable=True),
    sa.Column('symbol_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ptcg_set_id'),
    sa.UniqueConstraint('tcgplayer_group_id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('ptcg_card_id', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('number_sort', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('supertype', sa.String(length=32), nullable=True),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('subtypes', sa.JSON(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('national_pokedex_numbers', sa.JSON(), nullable=True),
    sa.Column('image_small', sa.String(length=512), nullable=True),
    sa.Column('image_large', sa.String(length=512), nullable=True),
    sa.Column('dominant_color_lab', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ptcg_card_id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index('ix_card_set_number', ['set_id', 'number_sort'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('goal_type', sa.String(length=16), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('filter_json', sa.JSON(), nullable=True),
    sa.Column('target_condition', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_rate_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cards_per_pack', sa.Integer(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('sample_packs', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('min_per_box', sa.Integer(), nullable=True),
    sa.Column('max_per_box', sa.Integer(), nullable=True),
    sa.Column('exact_per_box', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['pull_rate_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('tcgplayer_product_id', sa.Integer(), nullable=True),
    sa.Column('tcgplayer_sub_type_name', sa.String(length=64), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'variant', name='uq_card_variant')
    )
    with op.batch_alter_table('card_variant', schema=None) as batch_op:
        batch_op.create_index('ix_variant_product', ['tcgplayer_product_id', 'tcgplayer_sub_type_name'], unique=False)

    op.create_table('pack_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('repeat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['pull_rate_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sealed_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('tcgplayer_product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('packs_per_unit', sa.Integer(), nullable=True),
    sa.Column('pack_config_id', sa.Integer(), nullable=True),
    sa.Column('msrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contains_promos', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pack_config_id'], ['pull_rate_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcgplayer_product_id')
    )
    op.create_table('simulation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.String(length=16), nullable=False),
    sa.Column('profile_version', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_run_cache_key'), ['cache_key'], unique=False)

    op.create_table('binder_placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('card_variant_id', sa.Integer(), nullable=True),
    sa.Column('insert_asset_id', sa.Integer(), nullable=True),
    sa.Column('spans_gutter', sa.Boolean(), nullable=False),
    sa.Column('z_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_variant_id'], ['card_variant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insert_asset_id'], ['insert_asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('card_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=8), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('grader', sa.String(length=16), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('acquired_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_variant_id'], ['card_variant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'card_variant_id', 'condition', 'language', 'is_graded', 'grade', name='uq_collection_item')
    )
    op.create_table('goal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('card_variant_id', sa.Integer(), nullable=False),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_variant_id'], ['card_variant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'card_variant_id', name='uq_goal_item')
    )
    op.create_table('sealed_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('sealed_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sealed_product_id'], ['sealed_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_slot_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('pool_filter_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pack_slot_id'], ['pack_slot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS current_price")
    op.drop_table('slot_outcome')
    op.drop_table('sealed_holding')
    op.drop_table('goal_item')
    op.drop_table('collection_item')
    op.drop_table('binder_placement')
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_run_cache_key'))

    op.drop_table('simulation_run')
    op.drop_table('sealed_product')
    op.drop_table('pack_slot')
    with op.batch_alter_table('card_variant', schema=None) as batch_op:
        batch_op.drop_index('ix_variant_product')

    op.drop_table('card_variant')
    op.drop_table('box_constraint')
    op.drop_table('pull_rate_profile')
    op.drop_table('goal')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index('ix_card_set_number')

    op.drop_table('card')
    op.drop_table('set')
    with op.batch_alter_table('price_point', schema=None) as batch_op:
        batch_op.drop_index('ix_price_observed_on')

    op.drop_table('price_point')
    op.drop_table('insert_asset')
    op.drop_table('collection')
    op.drop_table('binder')
    # ### end Alembic commands ###
