// Auto-generated demo fixture for the standalone binder-designer demo (VITE_DEMO_MODE).
// Card names/prices are illustrative placeholders, not verified against the real Surging
// Sparks set -- image URLs follow pokemontcg.io's real CDN pattern so art actually renders.
import type { CardOut, SetDetailOut, BinderOut } from "./types";

export const DEMO_SET_ID = 1;
export const DEMO_BINDER_ID = 1;

const DEMO_CARDS: CardOut[] = [
  {
    id: 1,
    ptcg_card_id: "sv8-001",
    number: "001",
    number_sort: 1,
    name: "Pikachu",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/1.png",
    image_large: "https://images.pokemontcg.io/sv8/1_hires.png",
    is_owned: true,
    variants: [
      {
        id: 1,
        variant: "normal",
        tcgplayer_product_id: 500001,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "6.92",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 2,
    ptcg_card_id: "sv8-002",
    number: "002",
    number_sort: 2,
    name: "Raichu",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/2.png",
    image_large: "https://images.pokemontcg.io/sv8/2_hires.png",
    is_owned: false,
    variants: [
      {
        id: 2,
        variant: "normal",
        tcgplayer_product_id: 500002,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "3.40",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 3,
    ptcg_card_id: "sv8-003",
    number: "003",
    number_sort: 3,
    name: "Eevee",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/3.png",
    image_large: "https://images.pokemontcg.io/sv8/3_hires.png",
    is_owned: true,
    variants: [
      {
        id: 3,
        variant: "normal",
        tcgplayer_product_id: 500003,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "16.55",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 4,
    ptcg_card_id: "sv8-004",
    number: "004",
    number_sort: 4,
    name: "Vaporeon",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/4.png",
    image_large: "https://images.pokemontcg.io/sv8/4_hires.png",
    is_owned: true,
    variants: [
      {
        id: 4,
        variant: "normal",
        tcgplayer_product_id: 500004,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "22.91",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 5,
    ptcg_card_id: "sv8-005",
    number: "005",
    number_sort: 5,
    name: "Jolteon",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/5.png",
    image_large: "https://images.pokemontcg.io/sv8/5_hires.png",
    is_owned: true,
    variants: [
      {
        id: 5,
        variant: "normal",
        tcgplayer_product_id: 500005,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "19.60",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 6,
    ptcg_card_id: "sv8-006",
    number: "006",
    number_sort: 6,
    name: "Flareon",
    supertype: "Pokémon",
    rarity: "Double Rare",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/6.png",
    image_large: "https://images.pokemontcg.io/sv8/6_hires.png",
    is_owned: true,
    variants: [
      {
        id: 6,
        variant: "normal",
        tcgplayer_product_id: 500006,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "4.22",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 7,
    ptcg_card_id: "sv8-007",
    number: "007",
    number_sort: 7,
    name: "Espeon",
    supertype: "Pokémon",
    rarity: "Illustration Rare",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/7.png",
    image_large: "https://images.pokemontcg.io/sv8/7_hires.png",
    is_owned: true,
    variants: [
      {
        id: 7,
        variant: "normal",
        tcgplayer_product_id: 500007,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "37.23",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 8,
    ptcg_card_id: "sv8-008",
    number: "008",
    number_sort: 8,
    name: "Umbreon",
    supertype: "Pokémon",
    rarity: "Ultra Rare",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/8.png",
    image_large: "https://images.pokemontcg.io/sv8/8_hires.png",
    is_owned: true,
    variants: [
      {
        id: 8,
        variant: "normal",
        tcgplayer_product_id: 500008,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "10.16",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 9,
    ptcg_card_id: "sv8-009",
    number: "009",
    number_sort: 9,
    name: "Charmander",
    supertype: "Pokémon",
    rarity: "Special Illustration Rare",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/9.png",
    image_large: "https://images.pokemontcg.io/sv8/9_hires.png",
    is_owned: false,
    variants: [
      {
        id: 9,
        variant: "normal",
        tcgplayer_product_id: 500009,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "42.65",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 10,
    ptcg_card_id: "sv8-010",
    number: "010",
    number_sort: 10,
    name: "Charmeleon",
    supertype: "Pokémon",
    rarity: "Hyper Rare",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/10.png",
    image_large: "https://images.pokemontcg.io/sv8/10_hires.png",
    is_owned: false,
    variants: [
      {
        id: 10,
        variant: "normal",
        tcgplayer_product_id: 500010,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "17.94",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 11,
    ptcg_card_id: "sv8-011",
    number: "011",
    number_sort: 11,
    name: "Charizard",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/11.png",
    image_large: "https://images.pokemontcg.io/sv8/11_hires.png",
    is_owned: false,
    variants: [
      {
        id: 11,
        variant: "normal",
        tcgplayer_product_id: 500011,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "2.24",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 12,
    ptcg_card_id: "sv8-012",
    number: "012",
    number_sort: 12,
    name: "Squirtle",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/12.png",
    image_large: "https://images.pokemontcg.io/sv8/12_hires.png",
    is_owned: false,
    variants: [
      {
        id: 12,
        variant: "normal",
        tcgplayer_product_id: 500012,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "13.14",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 13,
    ptcg_card_id: "sv8-013",
    number: "013",
    number_sort: 13,
    name: "Wartortle",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/13.png",
    image_large: "https://images.pokemontcg.io/sv8/13_hires.png",
    is_owned: true,
    variants: [
      {
        id: 13,
        variant: "normal",
        tcgplayer_product_id: 500013,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "5.43",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 14,
    ptcg_card_id: "sv8-014",
    number: "014",
    number_sort: 14,
    name: "Blastoise",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/14.png",
    image_large: "https://images.pokemontcg.io/sv8/14_hires.png",
    is_owned: true,
    variants: [
      {
        id: 14,
        variant: "normal",
        tcgplayer_product_id: 500014,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "36.75",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 15,
    ptcg_card_id: "sv8-015",
    number: "015",
    number_sort: 15,
    name: "Bulbasaur",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/15.png",
    image_large: "https://images.pokemontcg.io/sv8/15_hires.png",
    is_owned: true,
    variants: [
      {
        id: 15,
        variant: "normal",
        tcgplayer_product_id: 500015,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "26.23",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 16,
    ptcg_card_id: "sv8-016",
    number: "016",
    number_sort: 16,
    name: "Ivysaur",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/16.png",
    image_large: "https://images.pokemontcg.io/sv8/16_hires.png",
    is_owned: false,
    variants: [
      {
        id: 16,
        variant: "normal",
        tcgplayer_product_id: 500016,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "16.85",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 17,
    ptcg_card_id: "sv8-017",
    number: "017",
    number_sort: 17,
    name: "Venusaur",
    supertype: "Pokémon",
    rarity: "Double Rare",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/17.png",
    image_large: "https://images.pokemontcg.io/sv8/17_hires.png",
    is_owned: true,
    variants: [
      {
        id: 17,
        variant: "normal",
        tcgplayer_product_id: 500017,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "2.97",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 18,
    ptcg_card_id: "sv8-018",
    number: "018",
    number_sort: 18,
    name: "Alolan Diglett",
    supertype: "Pokémon",
    rarity: "Illustration Rare",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/18.png",
    image_large: "https://images.pokemontcg.io/sv8/18_hires.png",
    is_owned: true,
    variants: [
      {
        id: 18,
        variant: "normal",
        tcgplayer_product_id: 500018,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "9.39",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 19,
    ptcg_card_id: "sv8-019",
    number: "019",
    number_sort: 19,
    name: "Alolan Dugtrio",
    supertype: "Pokémon",
    rarity: "Ultra Rare",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/19.png",
    image_large: "https://images.pokemontcg.io/sv8/19_hires.png",
    is_owned: false,
    variants: [
      {
        id: 19,
        variant: "normal",
        tcgplayer_product_id: 500019,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "19.33",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 20,
    ptcg_card_id: "sv8-020",
    number: "020",
    number_sort: 20,
    name: "Meowth",
    supertype: "Pokémon",
    rarity: "Special Illustration Rare",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/20.png",
    image_large: "https://images.pokemontcg.io/sv8/20_hires.png",
    is_owned: true,
    variants: [
      {
        id: 20,
        variant: "normal",
        tcgplayer_product_id: 500020,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "26.41",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 21,
    ptcg_card_id: "sv8-021",
    number: "021",
    number_sort: 21,
    name: "Persian",
    supertype: "Pokémon",
    rarity: "Hyper Rare",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/21.png",
    image_large: "https://images.pokemontcg.io/sv8/21_hires.png",
    is_owned: true,
    variants: [
      {
        id: 21,
        variant: "normal",
        tcgplayer_product_id: 500021,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "13.59",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 22,
    ptcg_card_id: "sv8-022",
    number: "022",
    number_sort: 22,
    name: "Psyduck",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/22.png",
    image_large: "https://images.pokemontcg.io/sv8/22_hires.png",
    is_owned: false,
    variants: [
      {
        id: 22,
        variant: "normal",
        tcgplayer_product_id: 500022,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "31.50",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 23,
    ptcg_card_id: "sv8-023",
    number: "023",
    number_sort: 23,
    name: "Golduck",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/23.png",
    image_large: "https://images.pokemontcg.io/sv8/23_hires.png",
    is_owned: true,
    variants: [
      {
        id: 23,
        variant: "normal",
        tcgplayer_product_id: 500023,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "25.91",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 24,
    ptcg_card_id: "sv8-024",
    number: "024",
    number_sort: 24,
    name: "Growlithe",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/24.png",
    image_large: "https://images.pokemontcg.io/sv8/24_hires.png",
    is_owned: true,
    variants: [
      {
        id: 24,
        variant: "normal",
        tcgplayer_product_id: 500024,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "39.40",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 25,
    ptcg_card_id: "sv8-025",
    number: "025",
    number_sort: 25,
    name: "Arcanine",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/25.png",
    image_large: "https://images.pokemontcg.io/sv8/25_hires.png",
    is_owned: false,
    variants: [
      {
        id: 25,
        variant: "normal",
        tcgplayer_product_id: 500025,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "13.06",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 26,
    ptcg_card_id: "sv8-026",
    number: "026",
    number_sort: 26,
    name: "Poliwag",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/26.png",
    image_large: "https://images.pokemontcg.io/sv8/26_hires.png",
    is_owned: false,
    variants: [
      {
        id: 26,
        variant: "normal",
        tcgplayer_product_id: 500026,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "5.45",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 27,
    ptcg_card_id: "sv8-027",
    number: "027",
    number_sort: 27,
    name: "Poliwhirl",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/27.png",
    image_large: "https://images.pokemontcg.io/sv8/27_hires.png",
    is_owned: true,
    variants: [
      {
        id: 27,
        variant: "normal",
        tcgplayer_product_id: 500027,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "34.11",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 28,
    ptcg_card_id: "sv8-028",
    number: "028",
    number_sort: 28,
    name: "Poliwrath",
    supertype: "Pokémon",
    rarity: "Double Rare",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/28.png",
    image_large: "https://images.pokemontcg.io/sv8/28_hires.png",
    is_owned: true,
    variants: [
      {
        id: 28,
        variant: "normal",
        tcgplayer_product_id: 500028,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "22.08",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 29,
    ptcg_card_id: "sv8-029",
    number: "029",
    number_sort: 29,
    name: "Abra",
    supertype: "Pokémon",
    rarity: "Illustration Rare",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/29.png",
    image_large: "https://images.pokemontcg.io/sv8/29_hires.png",
    is_owned: true,
    variants: [
      {
        id: 29,
        variant: "normal",
        tcgplayer_product_id: 500029,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "30.12",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 30,
    ptcg_card_id: "sv8-030",
    number: "030",
    number_sort: 30,
    name: "Kadabra",
    supertype: "Pokémon",
    rarity: "Ultra Rare",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/30.png",
    image_large: "https://images.pokemontcg.io/sv8/30_hires.png",
    is_owned: false,
    variants: [
      {
        id: 30,
        variant: "normal",
        tcgplayer_product_id: 500030,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "25.85",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 31,
    ptcg_card_id: "sv8-031",
    number: "031",
    number_sort: 31,
    name: "Alakazam",
    supertype: "Pokémon",
    rarity: "Special Illustration Rare",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/31.png",
    image_large: "https://images.pokemontcg.io/sv8/31_hires.png",
    is_owned: false,
    variants: [
      {
        id: 31,
        variant: "normal",
        tcgplayer_product_id: 500031,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "14.22",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 32,
    ptcg_card_id: "sv8-032",
    number: "032",
    number_sort: 32,
    name: "Machop",
    supertype: "Pokémon",
    rarity: "Hyper Rare",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/32.png",
    image_large: "https://images.pokemontcg.io/sv8/32_hires.png",
    is_owned: false,
    variants: [
      {
        id: 32,
        variant: "normal",
        tcgplayer_product_id: 500032,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "26.81",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 33,
    ptcg_card_id: "sv8-033",
    number: "033",
    number_sort: 33,
    name: "Machoke",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/33.png",
    image_large: "https://images.pokemontcg.io/sv8/33_hires.png",
    is_owned: false,
    variants: [
      {
        id: 33,
        variant: "normal",
        tcgplayer_product_id: 500033,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "20.61",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 34,
    ptcg_card_id: "sv8-034",
    number: "034",
    number_sort: 34,
    name: "Machamp",
    supertype: "Pokémon",
    rarity: "Common",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/34.png",
    image_large: "https://images.pokemontcg.io/sv8/34_hires.png",
    is_owned: false,
    variants: [
      {
        id: 34,
        variant: "normal",
        tcgplayer_product_id: 500034,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "42.52",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 35,
    ptcg_card_id: "sv8-035",
    number: "035",
    number_sort: 35,
    name: "Geodude",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "sui",
    image_small: "https://images.pokemontcg.io/sv8/35.png",
    image_large: "https://images.pokemontcg.io/sv8/35_hires.png",
    is_owned: true,
    variants: [
      {
        id: 35,
        variant: "normal",
        tcgplayer_product_id: 500035,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "29.94",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 36,
    ptcg_card_id: "sv8-036",
    number: "036",
    number_sort: 36,
    name: "Graveler",
    supertype: "Pokémon",
    rarity: "Uncommon",
    artist: "PLANETA Mochizuki",
    image_small: "https://images.pokemontcg.io/sv8/36.png",
    image_large: "https://images.pokemontcg.io/sv8/36_hires.png",
    is_owned: true,
    variants: [
      {
        id: 36,
        variant: "normal",
        tcgplayer_product_id: 500036,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "31.61",
        owned_quantity: 1,
      },
    ],
  },
  {
    id: 37,
    ptcg_card_id: "sv8-037",
    number: "037",
    number_sort: 37,
    name: "Golem",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "5ban Graphics",
    image_small: "https://images.pokemontcg.io/sv8/37.png",
    image_large: "https://images.pokemontcg.io/sv8/37_hires.png",
    is_owned: false,
    variants: [
      {
        id: 37,
        variant: "normal",
        tcgplayer_product_id: 500037,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "44.69",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 38,
    ptcg_card_id: "sv8-038",
    number: "038",
    number_sort: 38,
    name: "Ponyta",
    supertype: "Pokémon",
    rarity: "Rare",
    artist: "Naoyo Kimura",
    image_small: "https://images.pokemontcg.io/sv8/38.png",
    image_large: "https://images.pokemontcg.io/sv8/38_hires.png",
    is_owned: false,
    variants: [
      {
        id: 38,
        variant: "normal",
        tcgplayer_product_id: 500038,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "12.91",
        owned_quantity: 0,
      },
    ],
  },
  {
    id: 39,
    ptcg_card_id: "sv8-039",
    number: "039",
    number_sort: 39,
    name: "Rapidash",
    supertype: "Pokémon",
    rarity: "Double Rare",
    artist: "Kagemaru Himeno",
    image_small: "https://images.pokemontcg.io/sv8/39.png",
    image_large: "https://images.pokemontcg.io/sv8/39_hires.png",
    is_owned: true,
    variants: [
      {
        id: 39,
        variant: "normal",
        tcgplayer_product_id: 500039,
        tcgplayer_sub_type_name: "Normal",
        is_canonical: true,
        market_price: "30.14",
        owned_quantity: 1,
      },
    ],
  },
];

/** Extra fields the Michi clustering demo reads that aren't part of the wire CardOut shape. */
export const DEMO_POKEDEX: Record<number, number> = {
  1: 25,
  2: 26,
  3: 133,
  4: 134,
  5: 135,
  6: 136,
  7: 196,
  8: 197,
  9: 4,
  10: 5,
  11: 6,
  12: 7,
  13: 8,
  14: 9,
  15: 1,
  16: 2,
  17: 3,
  18: 50,
  19: 51,
  20: 52,
  21: 53,
  22: 54,
  23: 55,
  24: 58,
  25: 59,
  26: 60,
  27: 61,
  28: 62,
  29: 63,
  30: 64,
  31: 65,
  32: 66,
  33: 67,
  34: 68,
  35: 74,
  36: 75,
  37: 76,
  38: 77,
  39: 78,
};

export const DEMO_SET: SetDetailOut = {
  id: DEMO_SET_ID,
  ptcg_set_id: "sv8",
  name: "Surging Sparks (demo set)",
  series: "Scarlet & Violet",
  printed_total: 39,
  total: 39,
  release_date: "2024/11/08",
  symbol_url: null,
  logo_url: null,
  cards: DEMO_CARDS,
  owned_count: 22,
  needed_count: 17,
};

export const DEMO_BINDER: BinderOut = {
  id: DEMO_BINDER_ID,
  name: "Surging Sparks Demo Binder",
  rows: 3,
  cols: 3,
  pages: 8,
  is_side_loading: true,
  gutter_mm: 8,
  notes: "Seeded for the portfolio-site demo -- try Auto-layout or Michi below.",
};

